### ISSUE TITLE
[Feature Request] More Tabs filters

### ISSUE THREAD

**Issue by Kylmakalle** [nicegram/Telegram-iOS#4]
• More Workmode-like tabs with other filters (chats/bots/channels)

[@nicegramchat/453](https://t.me/nicegramchat/453)

**Comment by Kylmakalle** [comment]
Waiting for 5.6 Telegram sources

**Comment by wesley-devmuis** [comment]
Does this include a Telegram Plus style tabs system? (Example: https://imag.malavida.com/mvimgbig/download-fs/plus-messenger-17043-4.jpg)

Because it'd be amazing to finally be able to have tabs for chats, groups, and channels all separate instead of only muted and non muted.

If this is not the issue for that, I'll make a feature request for it :)

**Comment by Kylmakalle** [comment]
First released in [Build 20](https://github.com/nicegram/Telegram-iOS/commit/2f9c232bf90fd0cd07f29879b9c44e40df52133d)

[Preview](https://imgur.com/a/jRCRtml)

@wesley-devmuis

**Comment by ThinkerLVK** [comment]
![Image](https://i.imgur.com/Rto583I.jpg)

@Kylmakalle 
What if the number of messages display on the right, and a tick to the left

**Comment by Kylmakalle** [comment]
Added Admin Tab
https://github.com/nicegram/Telegram-iOS/commit/1df5f2b4a88f459d58cb9f2c6942d1b9e0cfbc22
